### ISSUE TITLE
Source path "./ux/src/TwigComponent" is not found in composer install

### ISSUE THREAD

**Issue by atouzard** [weaverryan/live-demo#1]
Hi,
I just cloned the repo and tried `composer install`

The following error popped :
```
[RuntimeException]                                                                       
  Source path "./ux/src/TwigComponent" is not found for package symfony/ux-twig-component
```

Am I missing something ?

Inspiring keynote by the way ;)

**Comment by dbrekelmans** [comment]
I have it running without issues, so I assume it's something on your side.

**Comment by weaverryan** [comment]
You were just super fast! Or, I was super slow to get the last details fixed for the demo :). About 30 minutes after opening this, I removed some code that was needed before the release of the libraries - it should be working now.

Thanks for the issue!
